server:
  port: 8080

spring:
  application:
    name: seata-mq-one
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true

feign:
  hystrix:
    enabled: true